version: '3.1'

services:

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    expose:
      - "6379"

  app:
    build:
      context: .
    ports:
      - "8090:8090"
    expose:
      - "8090"